ARDUINO_DIR:= /usr/share/arduino
ARDMK_DIR:= /usr/share/arduino
AVR_TOOLS_DIR:= /usr/share/arduino/hardware/tools/avr

BOARD_TAG:= uno
MONITOR_PORT:= /dev/ttyACM0

ARDUINO_LIBS:=

include /usr/share/arduino/Arduino.mk

#------------------------------------------------------------------------------#
